### ISSUE TITLE
Chapter 5 Exercise 5.7

### ISSUE THREAD

**Issue by alanzplus** [chenyukang/eopl#15]
I think the `let` implementation of `ch5/07.scm` is not correct.

The environment of evaluating variables should used the current environment instead of the extended environment with each new variable.

So given following test case, the answer should be 1 instead of 2. (same in the book 74 page, 3.16)

```
let x = 30
in let x = -(x,1)
         y = -(x,2)
    in -(x,y)
```

I suggest the following solution

```
(let-exp-cont (vars exps body binding-eval-env body-eval-env saved-cont)
  (if (null? exps)
    (value-of/k body (extend-env (car vars) val body-eval-env) saved-cont)
    (value-of/k (car exps)
                binding-eval-env
                (let-exp-cont
                  (cdr vars)
                  (cdr exps)
                  body
                  binding-eval-env
                  (extend-env (car vars) val body-eval-env)
                  saved-cont))))

```

**Comment by chenyukang** [comment]
@alanzplus , Yes, you are right.
Could you please give an PR?
